# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: IObit.IObitUnlocker
PackageVersion: 1.2.0.1
PackageLocale: en-US
Publisher: IObit
PublisherUrl: https://www.iobit.com/en/index.php
PublisherSupportUrl: https://www.iobit.com/en/faq.php
PrivacyUrl: https://www.iobit.com/en/privacy.php
Author: IObit
PackageName: IObit Unlocker
PackageUrl: https://www.iobit.com/en/iobit-unlocker.php
License: Freeware
LicenseUrl: https://www.iobit.com/en/eula.php
Copyright: © 2005 - 2021 IObit. All Rights Reserved
CopyrightUrl: https://www.iobit.com/en/eula.php
ShortDescription: Manage and unlock locked files
Description: IObit Unlocker performs well in solving “cannot delete files”, “access is denied”, “The file is in use by another program or user", or "There has been a sharing violation” problems. With IObit Unlocker, you can manage all your files the way you want.
Moniker: unlocker
Tags:
- unlock
- files
- handles
ManifestType: defaultLocale
ManifestVersion: 1.0.0

